services:
  - type: web
    name: discord-kakao-bot
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node src/index.js
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_APPLICATION_ID
        sync: false
      - key: COMPLAINT_CHANNEL_ID
        sync: false
      - key: KAKAO_WEBHOOK_URL
        sync: false
      - key: PORT
        value: "10000" 