services:
  - type: web
    name: discord-kakao-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_APPLICATION_ID
        sync: false
      - key: COMPLAINT_CHANNEL_ID
        sync: false
      - key: KAKAO_WEBHOOK_URL
        sync: false
      - key: PORT
        value: "3000" 